sudo: required

services:
 - docker

before_install:
 - docker build -t sagebionetworks/mpower-statistics .

script:
 # Now run the tests.
 - docker run -w /mPowerStatistics/tests sagebionetworks/mpower-statistics bash -c "R --no-save < /mPowerStatistics/tests/testthat.R"
